import { SortOrder } from "../../util/SortOrder";

export type MseCodilityOrderByInput = {
  id?: SortOrder;
  testSessionId?: SortOrder;
  test?: SortOrder;
  lastName?: SortOrder;
  nick?: SortOrder;
  email?: SortOrder;
  phone?: SortOrder;
  lastSchoolAttended?: SortOrder;
  fieldOfStudy?: SortOrder;
  academicDegree?: SortOrder;
  programmingExperience?: SortOrder;
  profileUrl?: SortOrder;
  createDate?: SortOrder;
  startDate?: SortOrder;
  closeDate?: SortOrder;
  ips?: SortOrder;
  totalScore?: SortOrder;
  maxScore?: SortOrder;
  percentTotalScore?: SortOrder;
  percentCorrectness?: SortOrder;
  percentPerformance?: SortOrder;
  timeUsed?: SortOrder;
  similarityCheck?: SortOrder;
  task1Name?: SortOrder;
  task1Score?: SortOrder;
  task1Correctness?: SortOrder;
  task1Performance?: SortOrder;
  task2Name?: SortOrder;
  task2Score?: SortOrder;
  task2Correctness?: SortOrder;
  task2Performance?: SortOrder;
  task3Name?: SortOrder;
  task3Score?: SortOrder;
  task3Correctness?: SortOrder;
  task3Performance?: SortOrder;
  task4Name?: SortOrder;
  task4Score?: SortOrder;
  task4Correctness?: SortOrder;
  task4Performance?: SortOrder;
  application_id?: SortOrder;
};
