import { SortOrder } from "../../util/SortOrder";

export type ReviewOrderByInput = {
  reviewerId?: SortOrder;
  background?: SortOrder;
  grades?: SortOrder;
  statement?: SortOrder;
  comments?: SortOrder;
  point?: SortOrder;
  pointCertainty?: SortOrder;
  point2?: SortOrder;
  point2Certainty?: SortOrder;
  privateComments?: SortOrder;
  round2?: SortOrder;
  round3?: SortOrder;
  touched?: SortOrder;
  admitVote?: SortOrder;
  recruited?: SortOrder;
  gradName?: SortOrder;
  pertinentInfo?: SortOrder;
  adviseTime?: SortOrder;
  commitMoney?: SortOrder;
  fundSource?: SortOrder;
  round?: SortOrder;
  interview?: SortOrder;
  recommendations?: SortOrder;
  publications?: SortOrder;
  brilliance?: SortOrder;
  otherInterest?: SortOrder;
  supplementalReview?: SortOrder;
  facVote?: SortOrder;
  committeeVote?: SortOrder;
  rrank?: SortOrder;
  departmentId?: SortOrder;
  mseExperienceLen?: SortOrder;
  impressed?: SortOrder;
  updated?: SortOrder;
  application_id?: SortOrder;
  id?: SortOrder;
};
