import { ApplicationWhereUniqueInput } from "../application/ApplicationWhereUniqueInput";
import { Decimal } from "decimal.js";

export type ReviewCreateInput = {
  admitVote?: string | null;
  adviseTime: string;
  application: ApplicationWhereUniqueInput;
  background?: string | null;
  brilliance?: string | null;
  comments?: string | null;
  commitMoney: string;
  committeeVote?: string | null;
  departmentId?: number | null;
  facVote?: string | null;
  fundSource: string;
  grades?: string | null;
  gradName: string;
  impressed?: string | null;
  interview?: string | null;
  mseExperienceLen?: string | null;
  otherInterest?: string | null;
  pertinentInfo: string;
  point?: Decimal | null;
  point2?: Decimal | null;
  point2Certainty?: Decimal | null;
  pointCertainty?: Decimal | null;
  privateComments?: string | null;
  publications?: string | null;
  recommendations?: string | null;
  recruited?: boolean | null;
  reviewerId: number;
  round?: number | null;
  round2?: number | null;
  round3?: number | null;
  rrank?: string | null;
  statement?: string | null;
  supplementalReview?: number | null;
  touched: string;
};
