import { Decimal } from "decimal.js";
import { ApplicationWhereUniqueInput } from "../application/ApplicationWhereUniqueInput";

export type ReviewUpdateInput = {
  reviewerId?: number;
  background?: string | null;
  grades?: string | null;
  statement?: string | null;
  comments?: string | null;
  point?: Decimal | null;
  pointCertainty?: Decimal | null;
  point2?: Decimal | null;
  point2Certainty?: Decimal | null;
  privateComments?: string | null;
  round2?: number | null;
  round3?: number | null;
  touched?: string;
  admitVote?: string | null;
  recruited?: boolean | null;
  gradName?: string;
  pertinentInfo?: string;
  adviseTime?: string;
  commitMoney?: string;
  fundSource?: string;
  round?: number | null;
  interview?: string | null;
  recommendations?: string | null;
  publications?: string | null;
  brilliance?: string | null;
  otherInterest?: string | null;
  supplementalReview?: number | null;
  facVote?: string | null;
  committeeVote?: string | null;
  rrank?: string | null;
  departmentId?: number | null;
  mseExperienceLen?: string | null;
  impressed?: string | null;
  application?: ApplicationWhereUniqueInput;
};
