/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApplicationWhereUniqueInput } from "../../application/base/ApplicationWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsInt,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumMhciPrereqsCourseCourseType } from "./EnumMhciPrereqsCourseCourseType";
import { LuUsersUsertypeWhereUniqueInput } from "../../luUsersUsertype/base/LuUsersUsertypeWhereUniqueInput";
import { MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput } from "./MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput";

@InputType()
class MhciPrereqsCourseUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ApplicationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ApplicationWhereUniqueInput)
  @IsOptional()
  @Field(() => ApplicationWhereUniqueInput, {
    nullable: true,
  })
  application?: ApplicationWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumMhciPrereqsCourseCourseType,
  })
  @IsEnum(EnumMhciPrereqsCourseCourseType)
  @IsOptional()
  @Field(() => EnumMhciPrereqsCourseCourseType, {
    nullable: true,
  })
  course_type?:
    | "Design"
    | "Programming"
    | "Multi_way_ANOVA"
    | "Single_way_ANOVA"
    | "Multi_factor_regression"
    | "Single_factor_regression";

  @ApiProperty({
    required: false,
    type: () => LuUsersUsertypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LuUsersUsertypeWhereUniqueInput)
  @IsOptional()
  @Field(() => LuUsersUsertypeWhereUniqueInput, {
    nullable: true,
  })
  luUsersUsertypes?: LuUsersUsertypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () =>
      MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput,
  })
  @ValidateNested()
  @Type(() => MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput)
  @IsOptional()
  @Field(
    () => MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput,
    {
      nullable: true,
    }
  )
  mhciPrereqsCourseDatafiles?: MhciPrereqsCourseDatafileUpdateManyWithoutMhciPrereqsCoursesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  periodId?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  programId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  studentCourseGrade?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  studentCourseInstitution?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  studentCourseName?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  studentCourseTime?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  submittedToReviewer?: number;
}

export { MhciPrereqsCourseUpdateInput as MhciPrereqsCourseUpdateInput };
