/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SlateRecommend1CreateInput } from "./SlateRecommend1CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateSlateRecommend1Args {
  @ApiProperty({
    required: true,
    type: () => SlateRecommend1CreateInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend1CreateInput)
  @Field(() => SlateRecommend1CreateInput, { nullable: false })
  data!: SlateRecommend1CreateInput;
}

export { CreateSlateRecommend1Args as CreateSlateRecommend1Args };
