/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SlateRecommend1WhereInput } from "./SlateRecommend1WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class SlateRecommend1ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => SlateRecommend1WhereInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend1WhereInput)
  @IsOptional()
  @Field(() => SlateRecommend1WhereInput, {
    nullable: true,
  })
  every?: SlateRecommend1WhereInput;

  @ApiProperty({
    required: false,
    type: () => SlateRecommend1WhereInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend1WhereInput)
  @IsOptional()
  @Field(() => SlateRecommend1WhereInput, {
    nullable: true,
  })
  some?: SlateRecommend1WhereInput;

  @ApiProperty({
    required: false,
    type: () => SlateRecommend1WhereInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend1WhereInput)
  @IsOptional()
  @Field(() => SlateRecommend1WhereInput, {
    nullable: true,
  })
  none?: SlateRecommend1WhereInput;
}
export { SlateRecommend1ListRelationFilter as SlateRecommend1ListRelationFilter };
