export type DuolingoDatumCreateInput = {
  applicantId: number;
  applicationId: number;
  birthdate: Date;
  certificateUrl: string;
  certified: number;
  comprehensionSubscore: number;
  conversationSubscore: number;
  country: string;
  couponId: string;
  domain: string;
  email: string;
  embedUrl: string;
  firstName: string;
  fullName: string;
  givenNames: string;
  interviewUrl: string;
  language: string;
  lastName: string;
  literacySubscore: number;
  middleNames: string;
  overallScore: number;
  percentScore: number;
  productionSubscore: number;
  scale: number;
  school?: string | null;
  sessionId: string;
  surnames: string;
  testDate: Date;
  userId: string;
  verificationDate: Date;
};
