import { SortOrder } from "../../util/SortOrder";

export type TestusersInfoOrderByInput = {
  additionalinfo?: SortOrder;
  addressCurCity?: SortOrder;
  addressCurCountry?: SortOrder;
  addressCurPcode?: SortOrder;
  addressCurState?: SortOrder;
  addressCurStreet1?: SortOrder;
  addressCurStreet2?: SortOrder;
  addressCurStreet3?: SortOrder;
  addressCurStreet4?: SortOrder;
  addressCurTel?: SortOrder;
  addressCurTelMobile?: SortOrder;
  addressCurTelWork?: SortOrder;
  addressPermCity?: SortOrder;
  addressPermCountry?: SortOrder;
  addressPermPcode?: SortOrder;
  addressPermState?: SortOrder;
  addressPermStreet1?: SortOrder;
  addressPermStreet2?: SortOrder;
  addressPermStreet3?: SortOrder;
  addressPermStreet4?: SortOrder;
  addressPermTel?: SortOrder;
  addressPermTelMobile?: SortOrder;
  addressPermTelWork?: SortOrder;
  buckleyWaive?: SortOrder;
  citCountry?: SortOrder;
  company?: SortOrder;
  curPaRes?: SortOrder;
  dob?: SortOrder;
  ethnicity?: SortOrder;
  ethtest?: SortOrder;
  gender?: SortOrder;
  homepage?: SortOrder;
  id?: SortOrder;
  userId?: SortOrder;
  visastatus?: SortOrder;
};
