export type TestusersInfo = {
  additionalinfo: string | null;
  addressCurCity: string | null;
  addressCurCountry: number | null;
  addressCurPcode: string | null;
  addressCurState: number | null;
  addressCurStreet1: string | null;
  addressCurStreet2: string | null;
  addressCurStreet3: string | null;
  addressCurStreet4: string | null;
  addressCurTel: string | null;
  addressCurTelMobile: string | null;
  addressCurTelWork: string | null;
  addressPermCity: string | null;
  addressPermCountry: number | null;
  addressPermPcode: string | null;
  addressPermState: number | null;
  addressPermStreet1: string | null;
  addressPermStreet2: string | null;
  addressPermStreet3: string | null;
  addressPermStreet4: string | null;
  addressPermTel: string | null;
  addressPermTelMobile: string | null;
  addressPermTelWork: string | null;
  buckleyWaive: boolean | null;
  citCountry: number | null;
  company: string | null;
  curPaRes: string | null;
  dob: Date | null;
  ethnicity: number | null;
  ethtest: number | null;
  gender: string | null;
  homepage: string | null;
  id: number;
  userId: number;
  visastatus: number | null;
};
