import { SortOrder } from "../../util/SortOrder";

export type SlateRecommend3OrderByInput = {
  prefix?: SortOrder;
  first?: SortOrder;
  middle?: SortOrder;
  last?: SortOrder;
  reference3Type?: SortOrder;
  reference3Submitted?: SortOrder;
  reference3First?: SortOrder;
  reference3Last?: SortOrder;
  reference3Industry?: SortOrder;
  reference3Organization?: SortOrder;
  reference3Title?: SortOrder;
  reference3Email?: SortOrder;
  reference3Phone?: SortOrder;
  referenceNum3IsrmsRecommenderScore1?: SortOrder;
  referenceNum3IsrmsRecommenderScore10?: SortOrder;
  referenceNum3IsrmsRecommenderScore11?: SortOrder;
  referenceNum3IsrmsRecommenderScore12?: SortOrder;
  referenceNum3IsrmsRecommenderScore13?: SortOrder;
  referenceNum3IsrmsRecommenderScore14?: SortOrder;
  referenceNum3IsrmsRecommenderScore15?: SortOrder;
  referenceNum3IsrmsRecommenderScore2?: SortOrder;
  referenceNum3IsrmsRecommenderScore3?: SortOrder;
  referenceNum3IsrmsRecommenderScore4?: SortOrder;
  referenceNum3IsrmsRecommenderScore5?: SortOrder;
  referenceNum3IsrmsRecommenderScore6?: SortOrder;
  referenceNum3IsrmsRecommenderScore7?: SortOrder;
  referenceNum3IsrmsRecommenderScore8?: SortOrder;
  referenceNum3IsrmsRecommenderScore9?: SortOrder;
  referenceNum3MseRecommendationAdditional?: SortOrder;
  referenceNum3MseRecommendationComparison?: SortOrder;
  referenceNum3MseRecommendationHowKnown?: SortOrder;
  referenceNum3MseRecommendationProjectPerformance?: SortOrder;
  referenceNum3MseRecommendationStrengthsWeakness?: SortOrder;
  referenceNum3RecommenderScore1?: SortOrder;
  referenceNum3RecommenderScore2?: SortOrder;
  referenceNum3RecommenderScore3?: SortOrder;
  referenceNum3RecommenderScore4?: SortOrder;
  referenceNum3RecommenderScore5?: SortOrder;
  referenceNum3RecommenderScore6?: SortOrder;
  referenceNum3RecommenderScore7?: SortOrder;
  referenceNum3RecommenderScore8?: SortOrder;
  id?: SortOrder;
};
