/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Em2SupportingCourseworkWhereInput } from "./Em2SupportingCourseworkWhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Em2SupportingCourseworkOrderByInput } from "./Em2SupportingCourseworkOrderByInput";

@ArgsType()
class Em2SupportingCourseworkFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Em2SupportingCourseworkWhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Em2SupportingCourseworkWhereInput, { nullable: true })
  @Type(() => Em2SupportingCourseworkWhereInput)
  where?: Em2SupportingCourseworkWhereInput;

  @ApiProperty({
    required: false,
    type: [Em2SupportingCourseworkOrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Em2SupportingCourseworkOrderByInput], { nullable: true })
  @Type(() => Em2SupportingCourseworkOrderByInput)
  orderBy?: Array<Em2SupportingCourseworkOrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Em2SupportingCourseworkFindManyArgs as Em2SupportingCourseworkFindManyArgs };
