/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SlateRecommend2WhereUniqueInput } from "./SlateRecommend2WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { SlateRecommend2UpdateInput } from "./SlateRecommend2UpdateInput";

@ArgsType()
class UpdateSlateRecommend2Args {
  @ApiProperty({
    required: true,
    type: () => SlateRecommend2WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend2WhereUniqueInput)
  @Field(() => SlateRecommend2WhereUniqueInput, { nullable: false })
  where!: SlateRecommend2WhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => SlateRecommend2UpdateInput,
  })
  @ValidateNested()
  @Type(() => SlateRecommend2UpdateInput)
  @Field(() => SlateRecommend2UpdateInput, { nullable: false })
  data!: SlateRecommend2UpdateInput;
}

export { UpdateSlateRecommend2Args as UpdateSlateRecommend2Args };
