import { SortOrder } from "../../util/SortOrder";

export type UsersinstOrderByInput = {
  applicationId?: SortOrder;
  classRank?: SortOrder;
  collegeName?: SortOrder;
  convertedGpa?: SortOrder;
  datafileId?: SortOrder;
  dateEntered?: SortOrder;
  dateGrad?: SortOrder;
  dateLeft?: SortOrder;
  degree?: SortOrder;
  degreeLevel?: SortOrder;
  degreeLevelOther?: SortOrder;
  educationtype?: SortOrder;
  gpa?: SortOrder;
  gpaMajor?: SortOrder;
  gpaScale?: SortOrder;
  id?: SortOrder;
  instituteId?: SortOrder;
  joint?: SortOrder;
  jointInstituteId?: SortOrder;
  major1?: SortOrder;
  major2?: SortOrder;
  major3?: SortOrder;
  minor1?: SortOrder;
  minor2?: SortOrder;
  transscriptreceived?: SortOrder;
  userId?: SortOrder;
};
