export type Usersinst = {
  userId: number;
  applicationId: number | null;
  instituteId: number | null;
  collegeName: string | null;
  dateEntered: Date | null;
  dateGrad: Date | null;
  dateLeft: Date | null;
  degree: string | null;
  degreeLevel: number | null;
  degreeLevelOther: string | null;
  major1: string | null;
  major2: string | null;
  major3: string | null;
  minor1: string | null;
  minor2: string | null;
  gpa: string | null;
  gpaMajor: string | null;
  gpaScale: number | null;
  transscriptreceived: boolean | null;
  datafileId: number | null;
  educationtype: number;
  classRank: string | null;
  convertedGpa: string | null;
  joint: number | null;
  jointInstituteId: number | null;
  id: number;
};
