/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteTesttableforBansheeArgs } from "./DeleteTesttableforBansheeArgs";
import { TesttableforBansheeCountArgs } from "./TesttableforBansheeCountArgs";
import { TesttableforBansheeFindManyArgs } from "./TesttableforBansheeFindManyArgs";
import { TesttableforBansheeFindUniqueArgs } from "./TesttableforBansheeFindUniqueArgs";
import { TesttableforBanshee } from "./TesttableforBanshee";
import { TesttableforBansheeService } from "../testtableforBanshee.service";
@graphql.Resolver(() => TesttableforBanshee)
export class TesttableforBansheeResolverBase {
  constructor(protected readonly service: TesttableforBansheeService) {}

  async _testtableforBansheesMeta(
    @graphql.Args() args: TesttableforBansheeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TesttableforBanshee])
  async testtableforBanshees(
    @graphql.Args() args: TesttableforBansheeFindManyArgs
  ): Promise<TesttableforBanshee[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => TesttableforBanshee, { nullable: true })
  async testtableforBanshee(
    @graphql.Args() args: TesttableforBansheeFindUniqueArgs
  ): Promise<TesttableforBanshee | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TesttableforBanshee)
  async deleteTesttableforBanshee(
    @graphql.Args() args: DeleteTesttableforBansheeArgs
  ): Promise<TesttableforBanshee | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
