import { SortOrder } from "../../util/SortOrder";

export type MitsSlateRecommend2OrderByInput = {
  first?: SortOrder;
  id?: SortOrder;
  last?: SortOrder;
  middle?: SortOrder;
  prefix?: SortOrder;
  reference2Email?: SortOrder;
  reference2First?: SortOrder;
  reference2Industry?: SortOrder;
  reference2Last?: SortOrder;
  reference2Organization?: SortOrder;
  reference2Phone?: SortOrder;
  reference2Submitted?: SortOrder;
  reference2Title?: SortOrder;
  reference2Type?: SortOrder;
  referenceNum2IsrmsRecommenderScore1?: SortOrder;
  referenceNum2IsrmsRecommenderScore10?: SortOrder;
  referenceNum2IsrmsRecommenderScore11?: SortOrder;
  referenceNum2IsrmsRecommenderScore12?: SortOrder;
  referenceNum2IsrmsRecommenderScore13?: SortOrder;
  referenceNum2IsrmsRecommenderScore14?: SortOrder;
  referenceNum2IsrmsRecommenderScore15?: SortOrder;
  referenceNum2IsrmsRecommenderScore2?: SortOrder;
  referenceNum2IsrmsRecommenderScore3?: SortOrder;
  referenceNum2IsrmsRecommenderScore4?: SortOrder;
  referenceNum2IsrmsRecommenderScore5?: SortOrder;
  referenceNum2IsrmsRecommenderScore6?: SortOrder;
  referenceNum2IsrmsRecommenderScore7?: SortOrder;
  referenceNum2IsrmsRecommenderScore8?: SortOrder;
  referenceNum2IsrmsRecommenderScore9?: SortOrder;
  referenceNum2MseRecommendationAdditional?: SortOrder;
  referenceNum2MseRecommendationComparison?: SortOrder;
  referenceNum2MseRecommendationHowKnown?: SortOrder;
  referenceNum2MseRecommendationProjectPerformance?: SortOrder;
  referenceNum2MseRecommendationStrengthsWeakness?: SortOrder;
  referenceNum2RecommenderScore1?: SortOrder;
  referenceNum2RecommenderScore2?: SortOrder;
  referenceNum2RecommenderScore3?: SortOrder;
  referenceNum2RecommenderScore4?: SortOrder;
  referenceNum2RecommenderScore5?: SortOrder;
  referenceNum2RecommenderScore6?: SortOrder;
  referenceNum2RecommenderScore7?: SortOrder;
  referenceNum2RecommenderScore8?: SortOrder;
};
