/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApplicationAdminNote } from "../../applicationAdminNote/base/ApplicationAdminNote";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsInt,
  IsDate,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { LuUsersUsertype } from "../../luUsersUsertype/base/LuUsersUsertype";

@ObjectType()
class User {
  @ApiProperty({
    required: false,
    type: () => [ApplicationAdminNote],
  })
  @ValidateNested()
  @Type(() => ApplicationAdminNote)
  @IsOptional()
  applicationAdminNote?: Array<ApplicationAdminNote>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  firstname!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstNamePref!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  guid!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  initials!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  lastname!: string;

  @ApiProperty({
    required: false,
    type: () => [LuUsersUsertype],
  })
  @ValidateNested()
  @Type(() => LuUsersUsertype)
  @IsOptional()
  luUsersUsertypes?: Array<LuUsersUsertype>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  middlename!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  signupDate!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  suffix!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  verified!: boolean;
}

export { User as User };
