/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ApplicationDecisionIni as PrismaApplicationDecisionIni,
} from "@prisma/client";

export class ApplicationDecisionIniServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ApplicationDecisionIniCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniCountArgs>
  ): Promise<number> {
    return this.prisma.applicationDecisionIni.count(args);
  }

  async applicationDecisionInis<
    T extends Prisma.ApplicationDecisionIniFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniFindManyArgs>
  ): Promise<PrismaApplicationDecisionIni[]> {
    return this.prisma.applicationDecisionIni.findMany(args);
  }
  async applicationDecisionIni<
    T extends Prisma.ApplicationDecisionIniFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniFindUniqueArgs>
  ): Promise<PrismaApplicationDecisionIni | null> {
    return this.prisma.applicationDecisionIni.findUnique(args);
  }
  async createApplicationDecisionIni<
    T extends Prisma.ApplicationDecisionIniCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniCreateArgs>
  ): Promise<PrismaApplicationDecisionIni> {
    return this.prisma.applicationDecisionIni.create<T>(args);
  }
  async updateApplicationDecisionIni<
    T extends Prisma.ApplicationDecisionIniUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniUpdateArgs>
  ): Promise<PrismaApplicationDecisionIni> {
    return this.prisma.applicationDecisionIni.update<T>(args);
  }
  async deleteApplicationDecisionIni<
    T extends Prisma.ApplicationDecisionIniDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ApplicationDecisionIniDeleteArgs>
  ): Promise<PrismaApplicationDecisionIni> {
    return this.prisma.applicationDecisionIni.delete(args);
  }
}
