/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Em2FinancialSupportWhereInput } from "./Em2FinancialSupportWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Em2FinancialSupportListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Em2FinancialSupportWhereInput,
  })
  @ValidateNested()
  @Type(() => Em2FinancialSupportWhereInput)
  @IsOptional()
  @Field(() => Em2FinancialSupportWhereInput, {
    nullable: true,
  })
  every?: Em2FinancialSupportWhereInput;

  @ApiProperty({
    required: false,
    type: () => Em2FinancialSupportWhereInput,
  })
  @ValidateNested()
  @Type(() => Em2FinancialSupportWhereInput)
  @IsOptional()
  @Field(() => Em2FinancialSupportWhereInput, {
    nullable: true,
  })
  some?: Em2FinancialSupportWhereInput;

  @ApiProperty({
    required: false,
    type: () => Em2FinancialSupportWhereInput,
  })
  @ValidateNested()
  @Type(() => Em2FinancialSupportWhereInput)
  @IsOptional()
  @Field(() => Em2FinancialSupportWhereInput, {
    nullable: true,
  })
  none?: Em2FinancialSupportWhereInput;
}
export { Em2FinancialSupportListRelationFilter as Em2FinancialSupportListRelationFilter };
