import { AcoPal } from "../acoPal/AcoPal";
import { ApplicationAdminNote } from "../applicationAdminNote/ApplicationAdminNote";
import { Attendance } from "../attendance/Attendance";
import { CashnetPayment } from "../cashnetPayment/CashnetPayment";
import { Experience } from "../experience/Experience";
import { Fellowship } from "../fellowship/Fellowship";
import { Gmatscore } from "../gmatscore/Gmatscore";
import { Gresubjectscore } from "../gresubjectscore/Gresubjectscore";
import { Ieltsscore } from "../ieltsscore/Ieltsscore";
import { LuApplicationAdvisor } from "../luApplicationAdvisor/LuApplicationAdvisor";
import { LuApplicationAppreq } from "../luApplicationAppreq/LuApplicationAppreq";
import { LuApplicationCohort } from "../luApplicationCohort/LuApplicationCohort";
import { LuApplicationGroup } from "../luApplicationGroup/LuApplicationGroup";
import { LuApplicationProgram } from "../luApplicationProgram/LuApplicationProgram";
import { LuApplicationStartSemester } from "../luApplicationStartSemester/LuApplicationStartSemester";
import { MhciPrereq } from "../mhciPrereq/MhciPrereq";
import { MhciPrereqsCourse } from "../mhciPrereqsCourse/MhciPrereqsCourse";
import { MlArea } from "../mlArea/MlArea";
import { MlSupportingCoursework } from "../mlSupportingCoursework/MlSupportingCoursework";
import { MseAqa } from "../mseAqa/MseAqa";
import { MseCodility } from "../mseCodility/MseCodility";
import { Payment } from "../payment/Payment";
import { Decimal } from "decimal.js";
import { PeriodApplication } from "../periodApplication/PeriodApplication";
import { PromotionHistory } from "../promotionHistory/PromotionHistory";
import { Publication } from "../publication/Publication";
import { Recommend } from "../recommend/Recommend";
import { RegistrationFeePayment } from "../registrationFeePayment/RegistrationFeePayment";
import { RegistrationFeeStatus } from "../registrationFeeStatus/RegistrationFeeStatus";
import { Review } from "../review/Review";
import { RissFunding } from "../rissFunding/RissFunding";
import { RissMcnair } from "../rissMcnair/RissMcnair";
import { SpecialConsideration } from "../specialConsideration/SpecialConsideration";
import { StudentDecision } from "../studentDecision/StudentDecision";
import { StudentDecisionHistory } from "../studentDecisionHistory/StudentDecisionHistory";
import { TagMember } from "../tagMember/TagMember";

export type Application = {
  acoPal?: AcoPal | null;
  applicationAdminNote?: Array<ApplicationAdminNote>;
  area1: string | null;
  area2: string | null;
  area3: string | null;
  attendance?: Array<Attendance>;
  buckleywaive: boolean | null;
  cashnetPayment?: Array<CashnetPayment>;
  cnbc: number | null;
  complete: boolean;
  createdDate: Date | null;
  crossDeptProgs: string | null;
  crossDeptProgsOther: string | null;
  cups: boolean;
  curEnrolled: string;
  experience?: Array<Experience>;
  fellowships?: Array<Fellowship>;
  gmatscore?: Array<Gmatscore>;
  gresubjectscore?: Array<Gresubjectscore>;
  hide: boolean;
  honors: string | null;
  id: number;
  ieltsscore?: Array<Ieltsscore>;
  invitationEmailSent: string | null;
  luApplicationAdvisor?: Array<LuApplicationAdvisor>;
  luApplicationAppreqs?: Array<LuApplicationAppreq>;
  luApplicationCohort?: LuApplicationCohort | null;
  luApplicationGroups?: Array<LuApplicationGroup>;
  luApplicationPrograms?: Array<LuApplicationProgram>;
  luApplicationStartSemester?: LuApplicationStartSemester | null;
  mastersReviewWaiver: boolean;
  mhciPrereqs?: Array<MhciPrereq>;
  mhciPrereqsCourses?: Array<MhciPrereqsCourse>;
  mlArea?: Array<MlArea>;
  mlSupportingCoursework?: Array<MlSupportingCoursework>;
  mseAqa?: Array<MseAqa>;
  mseCodility?: MseCodility | null;
  name: string;
  notificationsent: Date | null;
  otherInst: string | null;
  paid: boolean;
  payment?: Array<Payment>;
  paymentamount: Decimal | null;
  paymentdate: Date | null;
  paymenttype: number | null;
  periodApplication?: Array<PeriodApplication>;
  pier: boolean;
  portfolioLink: string | null;
  portfolioPassword: string | null;
  portfoliosubmitted: boolean | null;
  previousCoursework: number | null;
  promotionHistory?: Array<PromotionHistory>;
  publication?: Array<Publication>;
  recommend?: Array<Recommend>;
  recordsPermission: string | null;
  recruitingEvent: string | null;
  referralToProgram: string | null;
  registrationFeePayment?: Array<RegistrationFeePayment>;
  registrationFeeStatus?: Array<RegistrationFeeStatus>;
  rejectionSent: string | null;
  review?: Array<Review>;
  rissFunding?: Array<RissFunding>;
  rissMcnair?: Array<RissMcnair>;
  round2: string | null;
  round3: string | null;
  sentToProgram: string;
  specialConsideration?: Array<SpecialConsideration>;
  statementofpurpose: string | null;
  studentCommit: boolean;
  studentDecision?: Array<StudentDecision>;
  studentDecisionHistory?: Array<StudentDecisionHistory>;
  submitted: boolean;
  submittedDate: Date | null;
  tagMembers?: Array<TagMember>;
  userId: number;
  waitlistSent: string | null;
  waive: boolean;
  waivedate: Date | null;
  waiveHigherFee: number;
  waiveToefl: number | null;
  womenfellowship: boolean;
};
