import { AcoPalWhereUniqueInput } from "../acoPal/AcoPalWhereUniqueInput";
import { ApplicationAdminNoteListRelationFilter } from "../applicationAdminNote/ApplicationAdminNoteListRelationFilter";
import { AttendanceListRelationFilter } from "../attendance/AttendanceListRelationFilter";
import { CashnetPaymentListRelationFilter } from "../cashnetPayment/CashnetPaymentListRelationFilter";
import { ExperienceListRelationFilter } from "../experience/ExperienceListRelationFilter";
import { FellowshipListRelationFilter } from "../fellowship/FellowshipListRelationFilter";
import { GmatscoreListRelationFilter } from "../gmatscore/GmatscoreListRelationFilter";
import { GresubjectscoreListRelationFilter } from "../gresubjectscore/GresubjectscoreListRelationFilter";
import { IeltsscoreListRelationFilter } from "../ieltsscore/IeltsscoreListRelationFilter";
import { LuApplicationAdvisorListRelationFilter } from "../luApplicationAdvisor/LuApplicationAdvisorListRelationFilter";
import { LuApplicationAppreqListRelationFilter } from "../luApplicationAppreq/LuApplicationAppreqListRelationFilter";
import { LuApplicationCohortWhereUniqueInput } from "../luApplicationCohort/LuApplicationCohortWhereUniqueInput";
import { LuApplicationGroupListRelationFilter } from "../luApplicationGroup/LuApplicationGroupListRelationFilter";
import { LuApplicationProgramListRelationFilter } from "../luApplicationProgram/LuApplicationProgramListRelationFilter";
import { LuApplicationStartSemesterWhereUniqueInput } from "../luApplicationStartSemester/LuApplicationStartSemesterWhereUniqueInput";
import { MhciPrereqListRelationFilter } from "../mhciPrereq/MhciPrereqListRelationFilter";
import { MhciPrereqsCourseListRelationFilter } from "../mhciPrereqsCourse/MhciPrereqsCourseListRelationFilter";
import { MlAreaListRelationFilter } from "../mlArea/MlAreaListRelationFilter";
import { MlSupportingCourseworkListRelationFilter } from "../mlSupportingCoursework/MlSupportingCourseworkListRelationFilter";
import { MseAqaListRelationFilter } from "../mseAqa/MseAqaListRelationFilter";
import { MseCodilityWhereUniqueInput } from "../mseCodility/MseCodilityWhereUniqueInput";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { PeriodApplicationListRelationFilter } from "../periodApplication/PeriodApplicationListRelationFilter";
import { PromotionHistoryListRelationFilter } from "../promotionHistory/PromotionHistoryListRelationFilter";
import { PublicationListRelationFilter } from "../publication/PublicationListRelationFilter";
import { RecommendListRelationFilter } from "../recommend/RecommendListRelationFilter";
import { RegistrationFeePaymentListRelationFilter } from "../registrationFeePayment/RegistrationFeePaymentListRelationFilter";
import { RegistrationFeeStatusListRelationFilter } from "../registrationFeeStatus/RegistrationFeeStatusListRelationFilter";
import { ReviewListRelationFilter } from "../review/ReviewListRelationFilter";
import { RissFundingListRelationFilter } from "../rissFunding/RissFundingListRelationFilter";
import { RissMcnairListRelationFilter } from "../rissMcnair/RissMcnairListRelationFilter";
import { SpecialConsiderationListRelationFilter } from "../specialConsideration/SpecialConsiderationListRelationFilter";
import { StudentDecisionListRelationFilter } from "../studentDecision/StudentDecisionListRelationFilter";
import { StudentDecisionHistoryListRelationFilter } from "../studentDecisionHistory/StudentDecisionHistoryListRelationFilter";
import { TagMemberListRelationFilter } from "../tagMember/TagMemberListRelationFilter";

export type ApplicationWhereInput = {
  acoPal?: AcoPalWhereUniqueInput;
  applicationAdminNote?: ApplicationAdminNoteListRelationFilter;
  attendance?: AttendanceListRelationFilter;
  cashnetPayment?: CashnetPaymentListRelationFilter;
  experience?: ExperienceListRelationFilter;
  fellowships?: FellowshipListRelationFilter;
  gmatscore?: GmatscoreListRelationFilter;
  gresubjectscore?: GresubjectscoreListRelationFilter;
  ieltsscore?: IeltsscoreListRelationFilter;
  luApplicationAdvisor?: LuApplicationAdvisorListRelationFilter;
  luApplicationAppreqs?: LuApplicationAppreqListRelationFilter;
  luApplicationCohort?: LuApplicationCohortWhereUniqueInput;
  luApplicationGroups?: LuApplicationGroupListRelationFilter;
  luApplicationPrograms?: LuApplicationProgramListRelationFilter;
  luApplicationStartSemester?: LuApplicationStartSemesterWhereUniqueInput;
  mhciPrereqs?: MhciPrereqListRelationFilter;
  mhciPrereqsCourses?: MhciPrereqsCourseListRelationFilter;
  mlArea?: MlAreaListRelationFilter;
  mlSupportingCoursework?: MlSupportingCourseworkListRelationFilter;
  mseAqa?: MseAqaListRelationFilter;
  mseCodility?: MseCodilityWhereUniqueInput;
  payment?: PaymentListRelationFilter;
  periodApplication?: PeriodApplicationListRelationFilter;
  promotionHistory?: PromotionHistoryListRelationFilter;
  publication?: PublicationListRelationFilter;
  recommend?: RecommendListRelationFilter;
  registrationFeePayment?: RegistrationFeePaymentListRelationFilter;
  registrationFeeStatus?: RegistrationFeeStatusListRelationFilter;
  review?: ReviewListRelationFilter;
  rissFunding?: RissFundingListRelationFilter;
  rissMcnair?: RissMcnairListRelationFilter;
  specialConsideration?: SpecialConsiderationListRelationFilter;
  studentDecision?: StudentDecisionListRelationFilter;
  studentDecisionHistory?: StudentDecisionHistoryListRelationFilter;
  tagMembers?: TagMemberListRelationFilter;
};
