import { AcoPalWhereUniqueInput } from "../acoPal/AcoPalWhereUniqueInput";
import { ApplicationAdminNoteUpdateManyWithoutApplicationsInput } from "./ApplicationAdminNoteUpdateManyWithoutApplicationsInput";
import { AttendanceUpdateManyWithoutApplicationsInput } from "./AttendanceUpdateManyWithoutApplicationsInput";
import { CashnetPaymentUpdateManyWithoutApplicationsInput } from "./CashnetPaymentUpdateManyWithoutApplicationsInput";
import { ExperienceUpdateManyWithoutApplicationsInput } from "./ExperienceUpdateManyWithoutApplicationsInput";
import { FellowshipUpdateManyWithoutApplicationsInput } from "./FellowshipUpdateManyWithoutApplicationsInput";
import { GmatscoreUpdateManyWithoutApplicationsInput } from "./GmatscoreUpdateManyWithoutApplicationsInput";
import { GresubjectscoreUpdateManyWithoutApplicationsInput } from "./GresubjectscoreUpdateManyWithoutApplicationsInput";
import { IeltsscoreUpdateManyWithoutApplicationsInput } from "./IeltsscoreUpdateManyWithoutApplicationsInput";
import { LuApplicationAdvisorUpdateManyWithoutApplicationsInput } from "./LuApplicationAdvisorUpdateManyWithoutApplicationsInput";
import { LuApplicationAppreqUpdateManyWithoutApplicationsInput } from "./LuApplicationAppreqUpdateManyWithoutApplicationsInput";
import { LuApplicationCohortWhereUniqueInput } from "../luApplicationCohort/LuApplicationCohortWhereUniqueInput";
import { LuApplicationGroupUpdateManyWithoutApplicationsInput } from "./LuApplicationGroupUpdateManyWithoutApplicationsInput";
import { LuApplicationProgramUpdateManyWithoutApplicationsInput } from "./LuApplicationProgramUpdateManyWithoutApplicationsInput";
import { LuApplicationStartSemesterWhereUniqueInput } from "../luApplicationStartSemester/LuApplicationStartSemesterWhereUniqueInput";
import { MhciPrereqUpdateManyWithoutApplicationsInput } from "./MhciPrereqUpdateManyWithoutApplicationsInput";
import { MhciPrereqsCourseUpdateManyWithoutApplicationsInput } from "./MhciPrereqsCourseUpdateManyWithoutApplicationsInput";
import { MlAreaUpdateManyWithoutApplicationsInput } from "./MlAreaUpdateManyWithoutApplicationsInput";
import { MlSupportingCourseworkUpdateManyWithoutApplicationsInput } from "./MlSupportingCourseworkUpdateManyWithoutApplicationsInput";
import { MseAqaUpdateManyWithoutApplicationsInput } from "./MseAqaUpdateManyWithoutApplicationsInput";
import { MseCodilityWhereUniqueInput } from "../mseCodility/MseCodilityWhereUniqueInput";
import { PaymentUpdateManyWithoutApplicationsInput } from "./PaymentUpdateManyWithoutApplicationsInput";
import { Decimal } from "decimal.js";
import { PeriodApplicationUpdateManyWithoutApplicationsInput } from "./PeriodApplicationUpdateManyWithoutApplicationsInput";
import { PromotionHistoryUpdateManyWithoutApplicationsInput } from "./PromotionHistoryUpdateManyWithoutApplicationsInput";
import { PublicationUpdateManyWithoutApplicationsInput } from "./PublicationUpdateManyWithoutApplicationsInput";
import { RecommendUpdateManyWithoutApplicationsInput } from "./RecommendUpdateManyWithoutApplicationsInput";
import { RegistrationFeePaymentUpdateManyWithoutApplicationsInput } from "./RegistrationFeePaymentUpdateManyWithoutApplicationsInput";
import { RegistrationFeeStatusUpdateManyWithoutApplicationsInput } from "./RegistrationFeeStatusUpdateManyWithoutApplicationsInput";
import { ReviewUpdateManyWithoutApplicationsInput } from "./ReviewUpdateManyWithoutApplicationsInput";
import { RissFundingUpdateManyWithoutApplicationsInput } from "./RissFundingUpdateManyWithoutApplicationsInput";
import { RissMcnairUpdateManyWithoutApplicationsInput } from "./RissMcnairUpdateManyWithoutApplicationsInput";
import { SpecialConsiderationUpdateManyWithoutApplicationsInput } from "./SpecialConsiderationUpdateManyWithoutApplicationsInput";
import { StudentDecisionUpdateManyWithoutApplicationsInput } from "./StudentDecisionUpdateManyWithoutApplicationsInput";
import { StudentDecisionHistoryUpdateManyWithoutApplicationsInput } from "./StudentDecisionHistoryUpdateManyWithoutApplicationsInput";
import { TagMemberUpdateManyWithoutApplicationsInput } from "./TagMemberUpdateManyWithoutApplicationsInput";

export type ApplicationUpdateInput = {
  acoPal?: AcoPalWhereUniqueInput | null;
  applicationAdminNote?: ApplicationAdminNoteUpdateManyWithoutApplicationsInput;
  area1?: string | null;
  area2?: string | null;
  area3?: string | null;
  attendance?: AttendanceUpdateManyWithoutApplicationsInput;
  buckleywaive?: boolean | null;
  cashnetPayment?: CashnetPaymentUpdateManyWithoutApplicationsInput;
  cnbc?: number | null;
  complete?: boolean;
  createdDate?: Date | null;
  crossDeptProgs?: string | null;
  crossDeptProgsOther?: string | null;
  cups?: boolean;
  curEnrolled?: string;
  experience?: ExperienceUpdateManyWithoutApplicationsInput;
  fellowships?: FellowshipUpdateManyWithoutApplicationsInput;
  gmatscore?: GmatscoreUpdateManyWithoutApplicationsInput;
  gresubjectscore?: GresubjectscoreUpdateManyWithoutApplicationsInput;
  hide?: boolean;
  honors?: string | null;
  ieltsscore?: IeltsscoreUpdateManyWithoutApplicationsInput;
  invitationEmailSent?: string | null;
  luApplicationAdvisor?: LuApplicationAdvisorUpdateManyWithoutApplicationsInput;
  luApplicationAppreqs?: LuApplicationAppreqUpdateManyWithoutApplicationsInput;
  luApplicationCohort?: LuApplicationCohortWhereUniqueInput | null;
  luApplicationGroups?: LuApplicationGroupUpdateManyWithoutApplicationsInput;
  luApplicationPrograms?: LuApplicationProgramUpdateManyWithoutApplicationsInput;
  luApplicationStartSemester?: LuApplicationStartSemesterWhereUniqueInput | null;
  mastersReviewWaiver?: boolean;
  mhciPrereqs?: MhciPrereqUpdateManyWithoutApplicationsInput;
  mhciPrereqsCourses?: MhciPrereqsCourseUpdateManyWithoutApplicationsInput;
  mlArea?: MlAreaUpdateManyWithoutApplicationsInput;
  mlSupportingCoursework?: MlSupportingCourseworkUpdateManyWithoutApplicationsInput;
  mseAqa?: MseAqaUpdateManyWithoutApplicationsInput;
  mseCodility?: MseCodilityWhereUniqueInput | null;
  name?: string;
  notificationsent?: Date | null;
  otherInst?: string | null;
  paid?: boolean;
  payment?: PaymentUpdateManyWithoutApplicationsInput;
  paymentamount?: Decimal | null;
  paymentdate?: Date | null;
  paymenttype?: number | null;
  periodApplication?: PeriodApplicationUpdateManyWithoutApplicationsInput;
  pier?: boolean;
  portfolioLink?: string | null;
  portfolioPassword?: string | null;
  portfoliosubmitted?: boolean | null;
  previousCoursework?: number | null;
  promotionHistory?: PromotionHistoryUpdateManyWithoutApplicationsInput;
  publication?: PublicationUpdateManyWithoutApplicationsInput;
  recommend?: RecommendUpdateManyWithoutApplicationsInput;
  recordsPermission?: string | null;
  recruitingEvent?: string | null;
  referralToProgram?: string | null;
  registrationFeePayment?: RegistrationFeePaymentUpdateManyWithoutApplicationsInput;
  registrationFeeStatus?: RegistrationFeeStatusUpdateManyWithoutApplicationsInput;
  rejectionSent?: string | null;
  review?: ReviewUpdateManyWithoutApplicationsInput;
  rissFunding?: RissFundingUpdateManyWithoutApplicationsInput;
  rissMcnair?: RissMcnairUpdateManyWithoutApplicationsInput;
  round2?: string | null;
  round3?: string | null;
  sentToProgram?: string;
  specialConsideration?: SpecialConsiderationUpdateManyWithoutApplicationsInput;
  statementofpurpose?: string | null;
  studentCommit?: boolean;
  studentDecision?: StudentDecisionUpdateManyWithoutApplicationsInput;
  studentDecisionHistory?: StudentDecisionHistoryUpdateManyWithoutApplicationsInput;
  submitted?: boolean;
  submittedDate?: Date | null;
  tagMembers?: TagMemberUpdateManyWithoutApplicationsInput;
  userId?: number;
  waitlistSent?: string | null;
  waive?: boolean;
  waivedate?: Date | null;
  waiveHigherFee?: number;
  waiveToefl?: number | null;
  womenfellowship?: boolean;
};
