import { Decimal } from "decimal.js";
import { AcoPalWhereUniqueInput } from "../acoPal/AcoPalWhereUniqueInput";
import { ApplicationAdminNoteCreateNestedManyWithoutApplicationsInput } from "./ApplicationAdminNoteCreateNestedManyWithoutApplicationsInput";
import { AttendanceCreateNestedManyWithoutApplicationsInput } from "./AttendanceCreateNestedManyWithoutApplicationsInput";
import { CashnetPaymentCreateNestedManyWithoutApplicationsInput } from "./CashnetPaymentCreateNestedManyWithoutApplicationsInput";
import { ExperienceCreateNestedManyWithoutApplicationsInput } from "./ExperienceCreateNestedManyWithoutApplicationsInput";
import { FellowshipCreateNestedManyWithoutApplicationsInput } from "./FellowshipCreateNestedManyWithoutApplicationsInput";
import { GmatscoreCreateNestedManyWithoutApplicationsInput } from "./GmatscoreCreateNestedManyWithoutApplicationsInput";
import { GresubjectscoreCreateNestedManyWithoutApplicationsInput } from "./GresubjectscoreCreateNestedManyWithoutApplicationsInput";
import { IeltsscoreCreateNestedManyWithoutApplicationsInput } from "./IeltsscoreCreateNestedManyWithoutApplicationsInput";
import { LuApplicationAdvisorCreateNestedManyWithoutApplicationsInput } from "./LuApplicationAdvisorCreateNestedManyWithoutApplicationsInput";
import { LuApplicationAppreqCreateNestedManyWithoutApplicationsInput } from "./LuApplicationAppreqCreateNestedManyWithoutApplicationsInput";
import { LuApplicationCohortWhereUniqueInput } from "../luApplicationCohort/LuApplicationCohortWhereUniqueInput";
import { LuApplicationGroupCreateNestedManyWithoutApplicationsInput } from "./LuApplicationGroupCreateNestedManyWithoutApplicationsInput";
import { LuApplicationProgramCreateNestedManyWithoutApplicationsInput } from "./LuApplicationProgramCreateNestedManyWithoutApplicationsInput";
import { LuApplicationStartSemesterWhereUniqueInput } from "../luApplicationStartSemester/LuApplicationStartSemesterWhereUniqueInput";
import { MhciPrereqCreateNestedManyWithoutApplicationsInput } from "./MhciPrereqCreateNestedManyWithoutApplicationsInput";
import { MhciPrereqsCourseCreateNestedManyWithoutApplicationsInput } from "./MhciPrereqsCourseCreateNestedManyWithoutApplicationsInput";
import { MlAreaCreateNestedManyWithoutApplicationsInput } from "./MlAreaCreateNestedManyWithoutApplicationsInput";
import { MlSupportingCourseworkCreateNestedManyWithoutApplicationsInput } from "./MlSupportingCourseworkCreateNestedManyWithoutApplicationsInput";
import { MseAqaCreateNestedManyWithoutApplicationsInput } from "./MseAqaCreateNestedManyWithoutApplicationsInput";
import { MseCodilityWhereUniqueInput } from "../mseCodility/MseCodilityWhereUniqueInput";
import { PaymentCreateNestedManyWithoutApplicationsInput } from "./PaymentCreateNestedManyWithoutApplicationsInput";
import { PeriodApplicationCreateNestedManyWithoutApplicationsInput } from "./PeriodApplicationCreateNestedManyWithoutApplicationsInput";
import { PromotionHistoryCreateNestedManyWithoutApplicationsInput } from "./PromotionHistoryCreateNestedManyWithoutApplicationsInput";
import { PublicationCreateNestedManyWithoutApplicationsInput } from "./PublicationCreateNestedManyWithoutApplicationsInput";
import { RecommendCreateNestedManyWithoutApplicationsInput } from "./RecommendCreateNestedManyWithoutApplicationsInput";
import { RegistrationFeePaymentCreateNestedManyWithoutApplicationsInput } from "./RegistrationFeePaymentCreateNestedManyWithoutApplicationsInput";
import { RegistrationFeeStatusCreateNestedManyWithoutApplicationsInput } from "./RegistrationFeeStatusCreateNestedManyWithoutApplicationsInput";
import { ReviewCreateNestedManyWithoutApplicationsInput } from "./ReviewCreateNestedManyWithoutApplicationsInput";
import { RissFundingCreateNestedManyWithoutApplicationsInput } from "./RissFundingCreateNestedManyWithoutApplicationsInput";
import { RissMcnairCreateNestedManyWithoutApplicationsInput } from "./RissMcnairCreateNestedManyWithoutApplicationsInput";
import { SpecialConsiderationCreateNestedManyWithoutApplicationsInput } from "./SpecialConsiderationCreateNestedManyWithoutApplicationsInput";
import { StudentDecisionCreateNestedManyWithoutApplicationsInput } from "./StudentDecisionCreateNestedManyWithoutApplicationsInput";
import { StudentDecisionHistoryCreateNestedManyWithoutApplicationsInput } from "./StudentDecisionHistoryCreateNestedManyWithoutApplicationsInput";
import { TagMemberCreateNestedManyWithoutApplicationsInput } from "./TagMemberCreateNestedManyWithoutApplicationsInput";

export type ApplicationCreateInput = {
  userId: number;
  name: string;
  submittedDate?: Date | null;
  submitted: boolean;
  createdDate?: Date | null;
  paid: boolean;
  paymentdate?: Date | null;
  paymentamount?: Decimal | null;
  paymenttype?: number | null;
  waive: boolean;
  waivedate?: Date | null;
  complete: boolean;
  statementofpurpose?: string | null;
  notificationsent?: Date | null;
  studentCommit: boolean;
  cups: boolean;
  womenfellowship: boolean;
  pier: boolean;
  cnbc?: number | null;
  portfoliosubmitted?: boolean | null;
  portfolioLink?: string | null;
  portfolioPassword?: string | null;
  area1?: string | null;
  area2?: string | null;
  area3?: string | null;
  buckleywaive?: boolean | null;
  referralToProgram?: string | null;
  recruitingEvent?: string | null;
  otherInst?: string | null;
  crossDeptProgs?: string | null;
  crossDeptProgsOther?: string | null;
  recordsPermission?: string | null;
  mastersReviewWaiver: boolean;
  sentToProgram: string;
  curEnrolled: string;
  honors?: string | null;
  round2?: string | null;
  round3?: string | null;
  rejectionSent?: string | null;
  waitlistSent?: string | null;
  previousCoursework?: number | null;
  hide: boolean;
  waiveHigherFee: number;
  invitationEmailSent?: string | null;
  waiveToefl?: number | null;
  acoPal?: AcoPalWhereUniqueInput | null;
  applicationAdminNote?: ApplicationAdminNoteCreateNestedManyWithoutApplicationsInput;
  attendance?: AttendanceCreateNestedManyWithoutApplicationsInput;
  cashnetPayment?: CashnetPaymentCreateNestedManyWithoutApplicationsInput;
  experience?: ExperienceCreateNestedManyWithoutApplicationsInput;
  fellowships?: FellowshipCreateNestedManyWithoutApplicationsInput;
  gmatscore?: GmatscoreCreateNestedManyWithoutApplicationsInput;
  gresubjectscore?: GresubjectscoreCreateNestedManyWithoutApplicationsInput;
  ieltsscore?: IeltsscoreCreateNestedManyWithoutApplicationsInput;
  luApplicationAdvisor?: LuApplicationAdvisorCreateNestedManyWithoutApplicationsInput;
  luApplicationAppreqs?: LuApplicationAppreqCreateNestedManyWithoutApplicationsInput;
  luApplicationCohort?: LuApplicationCohortWhereUniqueInput | null;
  luApplicationGroups?: LuApplicationGroupCreateNestedManyWithoutApplicationsInput;
  luApplicationPrograms?: LuApplicationProgramCreateNestedManyWithoutApplicationsInput;
  luApplicationStartSemester?: LuApplicationStartSemesterWhereUniqueInput | null;
  mhciPrereqs?: MhciPrereqCreateNestedManyWithoutApplicationsInput;
  mhciPrereqsCourses?: MhciPrereqsCourseCreateNestedManyWithoutApplicationsInput;
  mlArea?: MlAreaCreateNestedManyWithoutApplicationsInput;
  mlSupportingCoursework?: MlSupportingCourseworkCreateNestedManyWithoutApplicationsInput;
  mseAqa?: MseAqaCreateNestedManyWithoutApplicationsInput;
  mseCodility?: MseCodilityWhereUniqueInput | null;
  payment?: PaymentCreateNestedManyWithoutApplicationsInput;
  periodApplication?: PeriodApplicationCreateNestedManyWithoutApplicationsInput;
  promotionHistory?: PromotionHistoryCreateNestedManyWithoutApplicationsInput;
  publication?: PublicationCreateNestedManyWithoutApplicationsInput;
  recommend?: RecommendCreateNestedManyWithoutApplicationsInput;
  registrationFeePayment?: RegistrationFeePaymentCreateNestedManyWithoutApplicationsInput;
  registrationFeeStatus?: RegistrationFeeStatusCreateNestedManyWithoutApplicationsInput;
  review?: ReviewCreateNestedManyWithoutApplicationsInput;
  rissFunding?: RissFundingCreateNestedManyWithoutApplicationsInput;
  rissMcnair?: RissMcnairCreateNestedManyWithoutApplicationsInput;
  specialConsideration?: SpecialConsiderationCreateNestedManyWithoutApplicationsInput;
  studentDecision?: StudentDecisionCreateNestedManyWithoutApplicationsInput;
  studentDecisionHistory?: StudentDecisionHistoryCreateNestedManyWithoutApplicationsInput;
  tagMembers?: TagMemberCreateNestedManyWithoutApplicationsInput;
};
