import { ApplicationWhereUniqueInput } from "../application/ApplicationWhereUniqueInput";

export type StudentDecisionCreateInput = {
  acceptReasons?: string | null;
  admin?: number | null;
  affiliatedCmu?: boolean | null;
  affiliatedCmutxt?: string | null;
  application: ApplicationWhereUniqueInput;
  asian?: number | null;
  attendAcc?: string | null;
  black?: number | null;
  cau?: number | null;
  citCountry?: string | null;
  cityP?: string | null;
  countryP?: string | null;
  decision?: "accept" | "decline" | "defer" | "matriculate" | null;
  decisionReasons?: string | null;
  deferralReasons?: string | null;
  deferralSemester?: string | null;
  deferralYear?: string | null;
  dob?: Date | null;
  doneDiff?: string | null;
  errors?: string | null;
  gender?: string | null;
  genderOther?: string | null;
  hispanic?: number | null;
  hpi?: number | null;
  legalName?: string | null;
  maritalOther?: string | null;
  maritalStatus?: string | null;
  natAm?: number | null;
  optComm?: number | null;
  otherChoice?: string | null;
  otherChoiceLocation?: string | null;
  otherSchoolsAccepted?: string | null;
  otherSchoolsApplied?: string | null;
  postalP?: string | null;
  prefEmail?: string | null;
  prefName?: string | null;
  progLength?: string | null;
  programId: number;
  pronoun?: string | null;
  pronounOther?: string | null;
  stateP?: string | null;
  streetP1?: string | null;
  streetP2?: string | null;
  streetP3?: string | null;
  streetP4?: string | null;
  submitted?: boolean | null;
  telMobile?: string | null;
  visit?: boolean | null;
  visitComments?: string | null;
  visitHelpful?: boolean | null;
};
