/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  DecisionAoiRankMember as PrismaDecisionAoiRankMember,
} from "@prisma/client";

export class DecisionAoiRankMemberServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.DecisionAoiRankMemberCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberCountArgs>
  ): Promise<number> {
    return this.prisma.decisionAoiRankMember.count(args);
  }

  async decisionAoiRankMembers<
    T extends Prisma.DecisionAoiRankMemberFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberFindManyArgs>
  ): Promise<PrismaDecisionAoiRankMember[]> {
    return this.prisma.decisionAoiRankMember.findMany(args);
  }
  async decisionAoiRankMember<
    T extends Prisma.DecisionAoiRankMemberFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberFindUniqueArgs>
  ): Promise<PrismaDecisionAoiRankMember | null> {
    return this.prisma.decisionAoiRankMember.findUnique(args);
  }
  async createDecisionAoiRankMember<
    T extends Prisma.DecisionAoiRankMemberCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberCreateArgs>
  ): Promise<PrismaDecisionAoiRankMember> {
    return this.prisma.decisionAoiRankMember.create<T>(args);
  }
  async updateDecisionAoiRankMember<
    T extends Prisma.DecisionAoiRankMemberUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberUpdateArgs>
  ): Promise<PrismaDecisionAoiRankMember> {
    return this.prisma.decisionAoiRankMember.update<T>(args);
  }
  async deleteDecisionAoiRankMember<
    T extends Prisma.DecisionAoiRankMemberDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.DecisionAoiRankMemberDeleteArgs>
  ): Promise<PrismaDecisionAoiRankMember> {
    return this.prisma.decisionAoiRankMember.delete(args);
  }
}
