/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MhciPrereqsStatusService } from "../mhciPrereqsStatus.service";
import { MhciPrereqsStatusCreateInput } from "./MhciPrereqsStatusCreateInput";
import { MhciPrereqsStatus } from "./MhciPrereqsStatus";
import { MhciPrereqsStatusFindManyArgs } from "./MhciPrereqsStatusFindManyArgs";
import { MhciPrereqsStatusWhereUniqueInput } from "./MhciPrereqsStatusWhereUniqueInput";
import { MhciPrereqsStatusUpdateInput } from "./MhciPrereqsStatusUpdateInput";

export class MhciPrereqsStatusControllerBase {
  constructor(protected readonly service: MhciPrereqsStatusService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MhciPrereqsStatus })
  async createMhciPrereqsStatus(
    @common.Body() data: MhciPrereqsStatusCreateInput
  ): Promise<MhciPrereqsStatus> {
    return await this.service.createMhciPrereqsStatus({
      data: {
        ...data,

        mhciPrereqs: {
          connect: data.mhciPrereqs,
        },
      },
      select: {
        id: true,

        mhciPrereqs: {
          select: {
            id: true,
          },
        },

        programId: true,
        reviewerExplanation: true,
        reviewerLuUsersUsertypesId: true,
        reviewer_status: true,
        reviewerTimestamp: true,
        status3: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MhciPrereqsStatus] })
  @ApiNestedQuery(MhciPrereqsStatusFindManyArgs)
  async mhciPrereqsStatuses(
    @common.Req() request: Request
  ): Promise<MhciPrereqsStatus[]> {
    const args = plainToClass(MhciPrereqsStatusFindManyArgs, request.query);
    return this.service.mhciPrereqsStatuses({
      ...args,
      select: {
        id: true,

        mhciPrereqs: {
          select: {
            id: true,
          },
        },

        programId: true,
        reviewerExplanation: true,
        reviewerLuUsersUsertypesId: true,
        reviewer_status: true,
        reviewerTimestamp: true,
        status3: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mhciPrereqsStatus(
    @common.Param() params: MhciPrereqsStatusWhereUniqueInput
  ): Promise<MhciPrereqsStatus | null> {
    const result = await this.service.mhciPrereqsStatus({
      where: params,
      select: {
        id: true,

        mhciPrereqs: {
          select: {
            id: true,
          },
        },

        programId: true,
        reviewerExplanation: true,
        reviewerLuUsersUsertypesId: true,
        reviewer_status: true,
        reviewerTimestamp: true,
        status3: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMhciPrereqsStatus(
    @common.Param() params: MhciPrereqsStatusWhereUniqueInput,
    @common.Body() data: MhciPrereqsStatusUpdateInput
  ): Promise<MhciPrereqsStatus | null> {
    try {
      return await this.service.updateMhciPrereqsStatus({
        where: params,
        data: {
          ...data,

          mhciPrereqs: {
            connect: data.mhciPrereqs,
          },
        },
        select: {
          id: true,

          mhciPrereqs: {
            select: {
              id: true,
            },
          },

          programId: true,
          reviewerExplanation: true,
          reviewerLuUsersUsertypesId: true,
          reviewer_status: true,
          reviewerTimestamp: true,
          status3: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMhciPrereqsStatus(
    @common.Param() params: MhciPrereqsStatusWhereUniqueInput
  ): Promise<MhciPrereqsStatus | null> {
    try {
      return await this.service.deleteMhciPrereqsStatus({
        where: params,
        select: {
          id: true,

          mhciPrereqs: {
            select: {
              id: true,
            },
          },

          programId: true,
          reviewerExplanation: true,
          reviewerLuUsersUsertypesId: true,
          reviewer_status: true,
          reviewerTimestamp: true,
          status3: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
