export type ReviewIniCreateInput = {
  applicationId: number;
  reviewerId: number;
  departmentId: number;
  round?: number | null;
  technicalComments: string;
  academicComments: string;
  academicProgramComments: string;
  researchComments?: string | null;
  workExperienceComments?: string | null;
  leadershipComments?: string | null;
  additionalComments?: string | null;
  ugProgramComments?: string | null;
  technicalRating: number;
  academicRating: number;
  researchRating?: number | null;
  workExperienceRating?: number | null;
  leadershipRating?: number | null;
  overallRating: number;
  alternativeProgram?: number | null;
};
