import { SortOrder } from "../../util/SortOrder";

export type MitsSlateCodilityOrderByInput = {
  codilityCloseDate?: SortOrder;
  codilityCreateDate?: SortOrder;
  codilityIpAddresses?: SortOrder;
  codilityMaxScore?: SortOrder;
  codilityPercentCorrectness?: SortOrder;
  codilityPercentPerformance?: SortOrder;
  codilityPercentTotalScore?: SortOrder;
  codilityScore?: SortOrder;
  codilitySimilarity?: SortOrder;
  codilityStartDate?: SortOrder;
  codilityTask1Correctness?: SortOrder;
  codilityTask1Difficulty?: SortOrder;
  codilityTask1Language?: SortOrder;
  codilityTask1Name?: SortOrder;
  codilityTask1Performance?: SortOrder;
  codilityTask1Score?: SortOrder;
  codilityTask2Correctness?: SortOrder;
  codilityTask2Difficulty?: SortOrder;
  codilityTask2Language?: SortOrder;
  codilityTask2Name?: SortOrder;
  codilityTask2Performance?: SortOrder;
  codilityTask2Score?: SortOrder;
  codilityTask3Correctness?: SortOrder;
  codilityTask3Difficulty?: SortOrder;
  codilityTask3Language?: SortOrder;
  codilityTask3Name?: SortOrder;
  codilityTask3Performance?: SortOrder;
  codilityTask3Score?: SortOrder;
  codilityTask4Correctness?: SortOrder;
  codilityTask4Difficulty?: SortOrder;
  codilityTask4Language?: SortOrder;
  codilityTask4Name?: SortOrder;
  codilityTask4Performance?: SortOrder;
  codilityTask4Score?: SortOrder;
  codilityTestName?: SortOrder;
  codilityTestSession?: SortOrder;
  first?: SortOrder;
  id?: SortOrder;
  last?: SortOrder;
  middle?: SortOrder;
  prefix?: SortOrder;
};
