import { SortOrder } from "../../util/SortOrder";

export type SlateRecommendOrderByInput = {
  applicationSlateGuid?: SortOrder;
  prefix?: SortOrder;
  first?: SortOrder;
  middle?: SortOrder;
  last?: SortOrder;
  reference1Type?: SortOrder;
  reference1Submitted?: SortOrder;
  reference1First?: SortOrder;
  reference1Last?: SortOrder;
  reference1Industry?: SortOrder;
  reference1Organization?: SortOrder;
  reference1Title?: SortOrder;
  reference1Email?: SortOrder;
  reference1Phone?: SortOrder;
  referenceNum1IsrmsRecommenderScore1?: SortOrder;
  referenceNum1IsrmsRecommenderScore10?: SortOrder;
  referenceNum1IsrmsRecommenderScore11?: SortOrder;
  referenceNum1IsrmsRecommenderScore12?: SortOrder;
  referenceNum1IsrmsRecommenderScore13?: SortOrder;
  referenceNum1IsrmsRecommenderScore14?: SortOrder;
  referenceNum1IsrmsRecommenderScore15?: SortOrder;
  referenceNum1IsrmsRecommenderScore2?: SortOrder;
  referenceNum1IsrmsRecommenderScore3?: SortOrder;
  referenceNum1IsrmsRecommenderScore4?: SortOrder;
  referenceNum1IsrmsRecommenderScore5?: SortOrder;
  referenceNum1IsrmsRecommenderScore6?: SortOrder;
  referenceNum1IsrmsRecommenderScore7?: SortOrder;
  referenceNum1IsrmsRecommenderScore8?: SortOrder;
  referenceNum1IsrmsRecommenderScore9?: SortOrder;
  referenceNum1MseRecommendationAdditional?: SortOrder;
  referenceNum1MseRecommendationComparison?: SortOrder;
  referenceNum1MseRecommendationHowKnown?: SortOrder;
  referenceNum1MseRecommendationProjectPerformance?: SortOrder;
  referenceNum1MseRecommendationStrengthsWeakness?: SortOrder;
  referenceNum1RecommenderScore1?: SortOrder;
  referenceNum1RecommenderScore2?: SortOrder;
  referenceNum1RecommenderScore3?: SortOrder;
  referenceNum1RecommenderScore4?: SortOrder;
  referenceNum1RecommenderScore5?: SortOrder;
  referenceNum1RecommenderScore6?: SortOrder;
  referenceNum1RecommenderScore7?: SortOrder;
  referenceNum1RecommenderScore8?: SortOrder;
  id?: SortOrder;
};
